version: '2'
services:
  skeletor:
    ports:
      - "5000:5000"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/go/src/skeletor"
    depends_on:
      - postgres
      
  postgres:
    ports:
      - 5432:5432
    build:
      context: ./sql
      dockerfile: Dockerfile
